apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  namespace: argocd   
  labels:
    app.kubernetes.io/name: argocd-secret 
    app.kubernetes.io/part-of: argocd       
type: Opaque 
stringData:
  dex.github.clientId: Ov23lixdSChAcIe13UY1
  dex.github.clientSecret: 21c0c40719b40c08931008db92160dc436a5fe86
