apiVersion: apps/v1
kind: Deployment
metadata:
  name: online-shop
  namespace: online-shop-prod
  annotations:
    # Assign alias 'chai-app' to your image
    argocd-image-updater.argoproj.io/image-list: online-shop=mikey699/online-devops
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/argocd-image-updater-git-creds 
    argocd-image-updater.argoproj.io/chai-app.update-strategy: semver  
spec:
  replicas: 3
  selector:
    matchLabels:
      app: online-shop
  template:
    metadata:
      labels:
        app: online-shop
    spec:
      containers:
      - name: online-shop
        image: mikey699/online:v1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: online-shop-config
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "300m"
            memory: "256Mi"
