apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: frontend-team
  namespace: argocd

spec:
  description: Frontend-team Project

  sourceRepos:
    - https://github.com/Hemasundar123/online_shopping_app.git

  destinations:
    - namespace: nginx
      server: https://172.17.0.1:33893

    - namespace: argocd
      server: https://172.17.0.1:33893

  clusterResourceWhitelist:
    - group: "*"
      kind: "*"

  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"

  roles:
    - name: frontend-admins
      description: Admins of Frontend-Project
      policies:
        - p,proj:frontend-team:frontend-admins,applications, *, frontend-team/*, allow
