name: github-actions-ci
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  IMAGE_NAME: shopping
  IMAGE_TAG: ${{ github.sha }}

jobs:
    login:
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repository
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Run a one-line script

              run: echo "Logging in to DockerHub"
            - name: Login to DockerHub
              uses: docker/login-action@v3
              with:
                username: ${{ vars.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD}}

            - name: Verify Docker Login
              run: docker info

            - name: Build and push Docker image
              uses: docker/build-push-action@v3
              with:
                context: .
                file: ./Dockerfile
                push: ${{ github.ref == 'refs/heads/master' }}
                tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
                cache-from: type=gha
                cache-to: type=gha,mode=max

            - name: Image build summary
              run: echo "Docker image ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} built and pushed successfully."

            - name: Trigger CD Workflow
              if: github.ref == 'refs/heads/master'
              uses: peter-evans/repository-dispatch@v3
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
                event-type: trigger-cd
                client-payload: '{"image_tag": "${{ env.IMAGE_TAG }}", "sha": "${{ env.IMAGE_TAG }}"}'
            
    